# Give a workflow name
name: pw test
# When run tests
on:  
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
# Job itself
jobs:
  #job name
  e2eTest:
    timeout-minutes: 60
    # set environment
    runs-on: ubuntu-latest
    steps:
    # make checkout
      - uses: actions/checkout@v4
    # set up Node
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
    # set up dependencies / npm ci
      - run: npm i
    # set up PW
      - name: Install PW
        run: npx playwright install --with-deps
      - name: Run PW test
        run: npm run test
    # save report pw
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: test-results
          path: test-results
          retention-days: 20
    # save report allure
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: allure-results
          path: allure-results
          retention-days: 20
    # get allure results of previous launch  
      - uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
    # form from allure-results -> allure-report
      - uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
    
    # deploy report
      - name: Deploy report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history  # default: gh-pages
